DROP TABLE PERSONNE

CREATE TABLE PERSONNE
(
	[id] INT IDENTITY(1,1) NOT NULL,
	[titre] VARCHAR(5) NOT NULL,
	[prenom] VARCHAR(50) NOT NULL,
	[nom] VARCHAR(50) NOT NULL,
	[email] VARCHAR(50) NOT NULL,
	[telephone] VARCHAR(17) NOT NULL,
	PRIMARY KEY CLUSTERED ([id]ASC)
)